name: vetting-app
recipe: wordpress
config:
  webroot: wordpress
  php: '7.3'
  xdebug: true
  via: nginx

services:
  appserver:
    config:
      conf:
        php: .php.ini
    run:
      - bash /app/bin/setup.sh
    build_as_root:
      - apt-get update -y && apt-get install -y subversion
    overrides:
      environment:
        WP_TESTS_DIR: /app/wordpress
      volumes:
        - ".:/app/wordpress/wp-content/plugins/vetting-events"

  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
    overrides:
      environment:
        PMA_USER: wordpress
        PMA_PASSWORD: wordpress

  mail:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver

tooling:
  phpunit:
    service: appserver
    description: "Run PHP unit tests: lando phpunit"
    cmd: composer test

  lint:
    service: appserver
    description: "Runs PHP linting tests: lando lint"
    cmd: composer lint

proxy:
  mail:
    - mail.lndo.site

  phpmyadmin:
    - sql.lndo.site
