name: vetting-app
recipe: wordpress
config:
  webroot: wordpress
  php: '7.3'
  xdebug: true
  via: nginx

services:
  appserver:
    overrides:
      volumes:
        - ".:/app/wordpress/wp-content/plugins/vetting-events"