name: vetting-app
recipe: wordpress
config:
  webroot: wordpress
  php: '7.3'
  xdebug: true
  via: nginx

services:
  appserver:
    overrides:
      volumes:
        - ".:/app/wordpress/wp-content/plugins/vetting-events"

  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
    overrides:
      environment:
        PMA_USER: wordpress
        PMA_PASSWORD: wordpress

  mail:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver

tooling:
  phpunit:
    service: appserver
    description: "Run PHP unit tests: lando phpunit"
